-- Private schema. Existing opaque-session authentication is checked in the API.
-- This migration does not enable Supabase Auth or public Realtime subscriptions.
BEGIN;
CREATE SCHEMA ojiisan;
REVOKE ALL ON SCHEMA ojiisan FROM PUBLIC, anon, authenticated;
CREATE TABLE ojiisan.profiles (
 id text PRIMARY KEY, auth_key text NOT NULL UNIQUE, nickname text NOT NULL,
 language text NOT NULL, level text NOT NULL, avatar text NOT NULL,
 available integer NOT NULL DEFAULT 1 CHECK (available IN (0,1)),
 last_seen bigint NOT NULL, created_at bigint NOT NULL
);
CREATE INDEX idx_profiles_presence ON ojiisan.profiles(available,last_seen);
CREATE TABLE ojiisan.rooms (
 id text PRIMARY KEY, kind text NOT NULL CHECK (kind IN ('dm','group')),
 title text NOT NULL, owner_id text NOT NULL REFERENCES ojiisan.profiles(id),
 dm_key text UNIQUE, created_at bigint NOT NULL, updated_at bigint NOT NULL
);
CREATE INDEX idx_rooms_owner ON ojiisan.rooms(owner_id);
CREATE TABLE ojiisan.members (
 room_id text NOT NULL REFERENCES ojiisan.rooms(id),
 user_id text NOT NULL REFERENCES ojiisan.profiles(id),
 state text NOT NULL CHECK (state IN ('pending','active','declined','left')),
 inviter_id text NOT NULL REFERENCES ojiisan.profiles(id),
 invited_at bigint NOT NULL, last_read bigint NOT NULL DEFAULT 0,
 PRIMARY KEY(room_id,user_id)
);
CREATE INDEX idx_members_user_state ON ojiisan.members(user_id,state);
CREATE INDEX idx_members_inviter_time ON ojiisan.members(inviter_id,invited_at);
CREATE TABLE ojiisan.messages (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 client_id text NOT NULL, room_id text NOT NULL REFERENCES ojiisan.rooms(id),
 user_id text NOT NULL REFERENCES ojiisan.profiles(id), japanese text NOT NULL,
 payload text NOT NULL, created_at bigint NOT NULL, UNIQUE(user_id,client_id)
);
CREATE INDEX idx_messages_room_id ON ojiisan.messages(room_id,id);
CREATE INDEX idx_messages_user_time ON ojiisan.messages(user_id,created_at);
CREATE TABLE ojiisan.blocks (
 user_id text NOT NULL REFERENCES ojiisan.profiles(id),
 target_id text NOT NULL REFERENCES ojiisan.profiles(id), created_at bigint NOT NULL,
 PRIMARY KEY(user_id,target_id)
);
CREATE INDEX idx_blocks_target ON ojiisan.blocks(target_id,user_id);
CREATE TABLE ojiisan.frontend_codes (
 code_hash text PRIMARY KEY, auth_key text NOT NULL, challenge text NOT NULL, expires_at bigint NOT NULL
);
CREATE INDEX idx_frontend_codes_user_expiry ON ojiisan.frontend_codes(auth_key,expires_at);
CREATE TABLE ojiisan.frontend_sessions (
 token_hash text PRIMARY KEY, auth_key text NOT NULL, expires_at bigint NOT NULL
);
CREATE INDEX idx_frontend_sessions_expiry ON ojiisan.frontend_sessions(expires_at);
CREATE TABLE ojiisan.study_progress (
 auth_key text NOT NULL, story_id text NOT NULL, step integer NOT NULL,
 due_at bigint NOT NULL, reviewed_at bigint NOT NULL, attempts integer NOT NULL,
 PRIMARY KEY(auth_key,story_id)
);
CREATE TABLE ojiisan.email_accounts (
 auth_key text PRIMARY KEY, email text NOT NULL UNIQUE, password_hash text NOT NULL,
 recovery_hash text NOT NULL, session_epoch integer NOT NULL DEFAULT 1,
 created_at bigint NOT NULL, updated_at bigint NOT NULL
);
CREATE TABLE ojiisan.account_sessions (
 token_hash text PRIMARY KEY, auth_key text NOT NULL REFERENCES ojiisan.email_accounts(auth_key),
 expires_at bigint NOT NULL, created_at bigint NOT NULL, session_epoch integer NOT NULL
);
CREATE INDEX idx_account_sessions_auth ON ojiisan.account_sessions(auth_key);
CREATE INDEX idx_account_sessions_expiry ON ojiisan.account_sessions(expires_at);
CREATE TABLE ojiisan.account_rate_limits (
 bucket text PRIMARY KEY, hits integer NOT NULL, expires_at bigint NOT NULL
);
CREATE INDEX idx_account_rates_expiry ON ojiisan.account_rate_limits(expires_at);
ALTER TABLE ojiisan.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE ojiisan.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE ojiisan.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE ojiisan.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE ojiisan.blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE ojiisan.frontend_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE ojiisan.frontend_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ojiisan.study_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE ojiisan.email_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE ojiisan.account_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ojiisan.account_rate_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ALL TABLES IN SCHEMA ojiisan FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA ojiisan FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA ojiisan REVOKE ALL ON TABLES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA ojiisan REVOKE ALL ON SEQUENCES FROM PUBLIC, anon, authenticated;
COMMIT;

-- Additive visit counter schema, also applied through Supabase migration history.
CREATE TABLE ojiisan.visit_totals (
 id text PRIMARY KEY CHECK (id='main'),
 visits bigint NOT NULL DEFAULT 0 CHECK (visits>=0),
 started_at bigint NOT NULL
);
CREATE TABLE ojiisan.visit_sessions (
 session_hash text PRIMARY KEY CHECK (length(session_hash)=43),
 expires_at bigint NOT NULL
);
CREATE INDEX idx_visit_sessions_expiry ON ojiisan.visit_sessions(expires_at);
ALTER TABLE ojiisan.visit_totals ENABLE ROW LEVEL SECURITY;
ALTER TABLE ojiisan.visit_sessions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ojiisan.visit_totals, ojiisan.visit_sessions FROM PUBLIC, anon, authenticated;
