export type StoryWord={id:string;jp:string;kana:string;icon:string;pt:string;en:string;grammar?:boolean};
export type Story={id:string;jp:string;pt:string;en:string;words:StoryWord[];scene:"sun"|"tea"|"park"|"book";notePt:string;noteEn:string};
const today:StoryWord={id:"story-today",jp:"今日",kana:"きょう",icon:"📅",pt:"hoje",en:"today"};
const wo:StoryWord={id:"story-wo",jp:"を",kana:"を",icon:"🎯",pt:"marca o objeto da ação",en:"marks the object of the action",grammar:true};
const wake:StoryWord={id:"story-wake",jp:"起きて",kana:"おきて",icon:"🌅",pt:"acordar e…",en:"wake up and…"};
export const stories:Story[]=[
 {id:"today-sun",jp:"今日、起きて、太陽を見ました。",pt:"Hoje acordei e olhei o sol.",en:"Today I woke up and looked at the sun.",scene:"sun",words:[today,wake,{id:"story-sun",jp:"太陽",kana:"たいよう",icon:"☀️",pt:"sol",en:"sun"},wo,{id:"story-saw",jp:"見ました",kana:"みました",icon:"👀",pt:"vi / olhei",en:"saw / looked"}],notePt:"起きて liga a primeira ação à seguinte. 見ました, no final, situa esta sequência no passado. O sol aparece antes de を e do verbo, seguindo o japonês.",noteEn:"起きて connects the first action to the next. Final 見ました places this sequence in the past. The sun comes before を and the verb, following Japanese order."},
 {id:"today-tea",jp:"今日、起きて、お茶を飲みました。",pt:"Hoje acordei e bebi chá.",en:"Today I woke up and drank tea.",scene:"tea",words:[today,wake,{id:"story-tea",jp:"お茶",kana:"おちゃ",icon:"🍵",pt:"chá",en:"tea"},wo,{id:"story-drank",jp:"飲みました",kana:"のみました",icon:"🥤",pt:"bebi",en:"drank"}],notePt:"O chá é o objeto de 飲みました. A partícula を mostra essa relação; ela não representa uma ação separada.",noteEn:"Tea is the object of 飲みました. The particle を shows that relation; it is not a separate action."},
 {id:"today-park",jp:"今日、公園に行きました。",pt:"Hoje fui ao parque.",en:"Today I went to the park.",scene:"park",words:[today,{id:"story-park",jp:"公園",kana:"こうえん",icon:"🏞️",pt:"parque",en:"park"},{id:"story-ni",jp:"に",kana:"に",icon:"➡️",pt:"marca o destino, aqui",en:"marks the destination here",grammar:true},{id:"story-went",jp:"行きました",kana:"いきました",icon:"🚶",pt:"fui",en:"went"}],notePt:"O destino vem antes do movimento: 公園 → に → 行きました. Neste exemplo, に marca para onde a pessoa foi.",noteEn:"The destination comes before movement: 公園 → に → 行きました. Here に marks where the person went."},
 {id:"today-book",jp:"今日、家で本を読みました。",pt:"Hoje li um livro em casa.",en:"Today I read a book at home.",scene:"book",words:[today,{id:"story-house",jp:"家",kana:"いえ",icon:"🏠",pt:"casa",en:"home"},{id:"story-de",jp:"で",kana:"で",icon:"📍",pt:"marca o local da ação",en:"marks the action's location",grammar:true},{id:"story-book",jp:"本",kana:"ほん",icon:"📖",pt:"livro",en:"book"},wo,{id:"story-read",jp:"読みました",kana:"よみました",icon:"📖",pt:"li",en:"read (past)"}],notePt:"家で indica onde a leitura aconteceu. 本を indica o que foi lido. A cena revela os elementos nessa mesma ordem.",noteEn:"家で shows where the reading happened. 本を shows what was read. The scene reveals the elements in that same order."},
];
export const storyById=Object.fromEntries(stories.map(s=>[s.id,s])) as Record<string,Story>;
